/**
 * @license Highcharts JS v8.0.4 (2020-03-10)
 *
 * Exporting module
 *
 * (c) 2010-2019 Torstein Honsi
 *
 * License: www.highcharts.com/license
 */
'use strict';(function(factory){if(typeof module==='object'&&module.exports){factory['default']=factory;module.exports=factory}else if(typeof define==='function'&&define.amd){define('highcharts/modules/exporting',['highcharts'],function(Highcharts){factory(Highcharts);factory.Highcharts=Highcharts;return factory})}else{factory(typeof Highcharts!=='undefined'?Highcharts:undefined)}}(function(Highcharts){var _modules=Highcharts?Highcharts._modules:{};function _registerModule(obj,path,args,fn){if(!obj.hasOwnProperty(path)){obj[path]=fn.apply(null,args)}}
_registerModule(_modules,'modules/full-screen.src.js',[_modules['parts/Globals.js']],function(H){var addEvent=H.addEvent,Chart=H.Chart;var Fullscreen=(function(){function Fullscreen(chart){this.chart=chart;this.isOpen=!1;if(!(chart.container.parentNode instanceof Element)){return}
var container=chart.container.parentNode;if(!this.browserProps){if(typeof container.requestFullscreen==='function'){this.browserProps={fullscreenChange:'fullscreenchange',requestFullscreen:'requestFullscreen',exitFullscreen:'exitFullscreen'}}else if(container.mozRequestFullScreen){this.browserProps={fullscreenChange:'mozfullscreenchange',requestFullscreen:'mozRequestFullScreen',exitFullscreen:'mozCancelFullScreen'}}else if(container.webkitRequestFullScreen){this.browserProps={fullscreenChange:'webkitfullscreenchange',requestFullscreen:'webkitRequestFullScreen',exitFullscreen:'webkitExitFullscreen'}}else if(container.msRequestFullscreen){this.browserProps={fullscreenChange:'MSFullscreenChange',requestFullscreen:'msRequestFullscreen',exitFullscreen:'msExitFullscreen'}}}}
Fullscreen.prototype.close=function(){var fullscreen=this,chart=fullscreen.chart;if(fullscreen.isOpen&&fullscreen.browserProps&&chart.container.ownerDocument instanceof Document){chart.container.ownerDocument[fullscreen.browserProps.exitFullscreen]()}
if(fullscreen.unbindFullscreenEvent){fullscreen.unbindFullscreenEvent()}
fullscreen.isOpen=!1;fullscreen.setButtonText()};Fullscreen.prototype.open=function(){var fullscreen=this,chart=fullscreen.chart;if(fullscreen.browserProps){fullscreen.unbindFullscreenEvent=H.addEvent(chart.container.ownerDocument,fullscreen.browserProps.fullscreenChange,function(){if(fullscreen.isOpen){fullscreen.isOpen=!1;fullscreen.close()}else{fullscreen.isOpen=!0;fullscreen.setButtonText()}});if(chart.container.parentNode instanceof Element){var promise=chart.container.parentNode[fullscreen.browserProps.requestFullscreen]();if(promise){promise['catch'](function(){alert('Full screen is not supported inside a frame.')})}}
H.addEvent(chart,'destroy',fullscreen.unbindFullscreenEvent)}};Fullscreen.prototype.setButtonText=function(){var _a;var chart=this.chart,exportDivElements=chart.exportDivElements,exportingOptions=chart.options.exporting,menuItems=(_a=exportingOptions===null||exportingOptions===void 0?void 0:exportingOptions.buttons)===null||_a===void 0?void 0:_a.contextButton.menuItems,lang=chart.options.lang;if((exportingOptions===null||exportingOptions===void 0?void 0:exportingOptions.menuItemDefinitions)&&(lang===null||lang===void 0?void 0:lang.exitFullscreen)&&lang.viewFullscreen&&menuItems&&exportDivElements&&exportDivElements.length){exportDivElements[menuItems.indexOf('viewFullscreen')].innerHTML=!this.isOpen?(exportingOptions.menuItemDefinitions.viewFullscreen.text||lang.viewFullscreen):lang.exitFullscreen}};Fullscreen.prototype.toggle=function(){var fullscreen=this;if(!fullscreen.isOpen){fullscreen.open()}else{fullscreen.close()}};return Fullscreen}());H.Fullscreen=Fullscreen;addEvent(Chart,'beforeRender',function(){this.fullscreen=new H.Fullscreen(this)});return H.Fullscreen});_registerModule(_modules,'mixins/navigation.js',[],function(){var chartNavigation={initUpdate:function(chart){if(!chart.navigation){chart.navigation={updates:[],update:function(options,redraw){this.updates.forEach(function(updateConfig){updateConfig.update.call(updateConfig.context,options,redraw)})}}}},addUpdate:function(update,chart){if(!chart.navigation){this.initUpdate(chart)}
chart.navigation.updates.push({update:update,context:chart})}};return chartNavigation});_registerModule(_modules,'modules/exporting.src.js',[_modules['parts/Globals.js'],_modules['parts/Utilities.js'],_modules['mixins/navigation.js']],function(H,U,chartNavigationMixin){var addEvent=U.addEvent,css=U.css,createElement=U.createElement,discardElement=U.discardElement,extend=U.extend,find=U.find,fireEvent=U.fireEvent,isObject=U.isObject,merge=U.merge,objectEach=U.objectEach,pick=U.pick,removeEvent=U.removeEvent,uniqueKey=U.uniqueKey;var defaultOptions=H.defaultOptions,doc=H.doc,Chart=H.Chart,isTouchDevice=H.isTouchDevice,win=H.win,userAgent=win.navigator.userAgent,SVGRenderer=H.SVGRenderer,symbols=H.Renderer.prototype.symbols,isMSBrowser=/Edge\/|Trident\/|MSIE /.test(userAgent),isFirefoxBrowser=/firefox/i.test(userAgent);extend(defaultOptions.lang,{viewFullscreen:'View in full screen',exitFullscreen:'Exit from full screen',printChart:'Print chart',downloadPNG:'Download PNG image',downloadJPEG:'Download JPEG image',downloadPDF:'Download PDF document',downloadSVG:'Download SVG vector image',contextButtonTitle:'Chart context menu'});if(!defaultOptions.navigation){defaultOptions.navigation={}}
merge(!0,defaultOptions.navigation,{buttonOptions:{theme:{},symbolSize:14,symbolX:12.5,symbolY:10.5,align:'right',buttonSpacing:3,height:22,verticalAlign:'top',width:24}});merge(!0,defaultOptions.navigation,{menuStyle:{border:'1px solid #999999',background:'#ffffff',padding:'5px 0'},menuItemStyle:{padding:'0.5em 1em',color:'#333333',background:'none',fontSize:isTouchDevice?'14px':'11px',transition:'background 250ms, color 250ms'},menuItemHoverStyle:{background:'#335cad',color:'#ffffff'},buttonOptions:{symbolFill:'#666666',symbolStroke:'#666666',symbolStrokeWidth:3,theme:{padding:5}}});defaultOptions.exporting={type:'image/png',url:'https://export.highcharts.com/',printMaxWidth:780,scale:2,buttons:{contextButton:{className:'highcharts-contextbutton',menuClassName:'highcharts-contextmenu',symbol:'menu',titleKey:'contextButtonTitle',menuItems:['viewFullscreen','printChart','separator','downloadPNG','downloadJPEG','downloadPDF','downloadSVG']}},menuItemDefinitions:{viewFullscreen:{textKey:'viewFullscreen',onclick:function(){this.fullscreen.toggle()}},printChart:{textKey:'printChart',onclick:function(){this.print()}},separator:{separator:!0},downloadPNG:{textKey:'downloadPNG',onclick:function(){this.exportChart()}},downloadJPEG:{textKey:'downloadJPEG',onclick:function(){this.exportChart({type:'image/jpeg'})}},downloadPDF:{textKey:'downloadPDF',onclick:function(){this.exportChart({type:'application/pdf'})}},downloadSVG:{textKey:'downloadSVG',onclick:function(){this.exportChart({type:'image/svg+xml'})}}}};H.post=function(url,data,formAttributes){var form=createElement('form',merge({method:'post',action:url,enctype:'multipart/form-data'},formAttributes),{display:'none'},doc.body);objectEach(data,function(val,name){createElement('input',{type:'hidden',name:name,value:val},null,form)});form.submit();discardElement(form)};if(H.isSafari){H.win.matchMedia('print').addListener(function(mqlEvent){if(!H.printingChart){return void 0}
if(mqlEvent.matches){H.printingChart.beforePrint()}else{H.printingChart.afterPrint()}})}
extend(Chart.prototype,{sanitizeSVG:function(svg,options){var split=svg.indexOf('</svg>')+6,html=svg.substr(split);svg=svg.substr(0,split);if(options&&options.exporting&&options.exporting.allowHTML){if(html){html='<foreignObject x="0" y="0" '+'width="'+options.chart.width+'" '+'height="'+options.chart.height+'">'+'<body xmlns="http://www.w3.org/1999/xhtml">'+html+'</body>'+'</foreignObject>';svg=svg.replace('</svg>',html+'</svg>')}}
svg=svg.replace(/zIndex="[^"]+"/g,'').replace(/symbolName="[^"]+"/g,'').replace(/jQuery[0-9]+="[^"]+"/g,'').replace(/url\(("|&quot;)(.*?)("|&quot;)\;?\)/g,'url($2)').replace(/url\([^#]+#/g,'url(#').replace(/<svg /,'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ (|NS[0-9]+\:)href=/g,' xlink:href=').replace(/\n/,' ').replace(/(fill|stroke)="rgba\(([ 0-9]+,[ 0-9]+,[ 0-9]+),([ 0-9\.]+)\)"/g,'$1="rgb($2)" $1-opacity="$3"').replace(/&nbsp;/g,'\u00A0').replace(/&shy;/g,'\u00AD');if(this.ieSanitizeSVG){svg=this.ieSanitizeSVG(svg)}
return svg},getChartHTML:function(){if(this.styledMode){this.inlineStyles()}
return this.container.innerHTML},getSVG:function(chartOptions){var chart=this,chartCopy,sandbox,svg,seriesOptions,sourceWidth,sourceHeight,cssWidth,cssHeight,options=merge(chart.options,chartOptions);options.plotOptions=merge(chart.userOptions.plotOptions,chartOptions&&chartOptions.plotOptions);options.time=merge(chart.userOptions.time,chartOptions&&chartOptions.time);sandbox=createElement('div',null,{position:'absolute',top:'-9999em',width:chart.chartWidth+'px',height:chart.chartHeight+'px'},doc.body);cssWidth=chart.renderTo.style.width;cssHeight=chart.renderTo.style.height;sourceWidth=options.exporting.sourceWidth||options.chart.width||(/px$/.test(cssWidth)&&parseInt(cssWidth,10))||(options.isGantt?800:600);sourceHeight=options.exporting.sourceHeight||options.chart.height||(/px$/.test(cssHeight)&&parseInt(cssHeight,10))||400;extend(options.chart,{animation:!1,renderTo:sandbox,forExport:!0,renderer:'SVGRenderer',width:sourceWidth,height:sourceHeight});options.exporting.enabled=!1;delete options.data;options.series=[];chart.series.forEach(function(serie){seriesOptions=merge(serie.userOptions,{animation:!1,enableMouseTracking:!1,showCheckbox:!1,visible:serie.visible});if(!seriesOptions.isInternal){options.series.push(seriesOptions)}});chart.axes.forEach(function(axis){if(!axis.userOptions.internalKey){axis.userOptions.internalKey=uniqueKey()}});chartCopy=new H.Chart(options,chart.callback);if(chartOptions){['xAxis','yAxis','series'].forEach(function(coll){var collOptions={};if(chartOptions[coll]){collOptions[coll]=chartOptions[coll];chartCopy.update(collOptions)}})}
chart.axes.forEach(function(axis){var axisCopy=find(chartCopy.axes,function(copy){return copy.options.internalKey===axis.userOptions.internalKey}),extremes=axis.getExtremes(),userMin=extremes.userMin,userMax=extremes.userMax;if(axisCopy&&((typeof userMin!=='undefined'&&userMin!==axisCopy.min)||(typeof userMax!=='undefined'&&userMax!==axisCopy.max))){axisCopy.setExtremes(userMin,userMax,!0,!1)}});svg=chartCopy.getChartHTML();fireEvent(this,'getSVG',{chartCopy:chartCopy});svg=chart.sanitizeSVG(svg,options);options=null;chartCopy.destroy();discardElement(sandbox);return svg},getSVGForExport:function(options,chartOptions){var chartExportingOptions=this.options.exporting;return this.getSVG(merge({chart:{borderRadius:0}},chartExportingOptions.chartOptions,chartOptions,{exporting:{sourceWidth:((options&&options.sourceWidth)||chartExportingOptions.sourceWidth),sourceHeight:((options&&options.sourceHeight)||chartExportingOptions.sourceHeight)}}))},getFilename:function(){var s=this.userOptions.title&&this.userOptions.title.text,filename=this.options.exporting.filename;if(filename){return filename.replace(/\//g,'-')}
if(typeof s==='string'){filename=s.toLowerCase().replace(/<\/?[^>]+(>|$)/g,'').replace(/[\s_]+/g,'-').replace(/[^a-z0-9\-]/g,'').replace(/^[\-]+/g,'').replace(/[\-]+/g,'-').substr(0,24).replace(/[\-]+$/g,'')}
if(!filename||filename.length<5){filename='chart'}
return filename},exportChart:function(exportingOptions,chartOptions){var svg=this.getSVGForExport(exportingOptions,chartOptions);exportingOptions=merge(this.options.exporting,exportingOptions);H.post(exportingOptions.url,{filename:exportingOptions.filename?exportingOptions.filename.replace(/\//g,'-'):this.getFilename(),type:exportingOptions.type,width:exportingOptions.width||0,scale:exportingOptions.scale,svg:svg},exportingOptions.formAttributes)},moveContainers:function(moveTo){var chart=this;(chart.fixedDiv?[chart.fixedDiv,chart.scrollingContainer]:[chart.container]).forEach(function(div){moveTo.appendChild(div)})},beforePrint:function(){var chart=this,body=doc.body,printMaxWidth=chart.options.exporting.printMaxWidth,printReverseInfo={childNodes:body.childNodes,origDisplay:[],resetParams:void 0};var handleMaxWidth;chart.isPrinting=!0;chart.pointer.reset(null,0);fireEvent(chart,'beforePrint');handleMaxWidth=printMaxWidth&&chart.chartWidth>printMaxWidth;if(handleMaxWidth){printReverseInfo.resetParams=[chart.options.chart.width,void 0,!1];chart.setSize(printMaxWidth,void 0,!1)}[].forEach.call(printReverseInfo.childNodes,function(node,i){if(node.nodeType===1){printReverseInfo.origDisplay[i]=node.style.display;node.style.display='none'}});chart.moveContainers(body);chart.printReverseInfo=printReverseInfo},afterPrint:function(){var chart=this;if(!chart.printReverseInfo){return void 0}
var childNodes=chart.printReverseInfo.childNodes,origDisplay=chart.printReverseInfo.origDisplay,resetParams=chart.printReverseInfo.resetParams;chart.moveContainers(chart.renderTo);[].forEach.call(childNodes,function(node,i){if(node.nodeType===1){node.style.display=(origDisplay[i]||'')}});chart.isPrinting=!1;if(resetParams){chart.setSize.apply(chart,resetParams)}
delete chart.printReverseInfo;delete H.printingChart;fireEvent(chart,'afterPrint')},print:function(){var chart=this;if(chart.isPrinting){return}
H.printingChart=chart;if(!H.isSafari){chart.beforePrint()}
setTimeout(function(){win.focus();win.print();if(!H.isSafari){setTimeout(function(){chart.afterPrint()},1000)}},1)},contextMenu:function(className,items,x,y,width,height,button){var chart=this,navOptions=chart.options.navigation,chartWidth=chart.chartWidth,chartHeight=chart.chartHeight,cacheName='cache-'+className,menu=chart[cacheName],menuPadding=Math.max(width,height),innerMenu,menuStyle;if(!menu){chart.exportContextMenu=chart[cacheName]=menu=createElement('div',{className:className},{position:'absolute',zIndex:1000,padding:menuPadding+'px',pointerEvents:'auto'},chart.fixedDiv||chart.container);innerMenu=createElement('ul',{className:'highcharts-menu'},{listStyle:'none',margin:0,padding:0},menu);if(!chart.styledMode){css(innerMenu,extend({MozBoxShadow:'3px 3px 10px #888',WebkitBoxShadow:'3px 3px 10px #888',boxShadow:'3px 3px 10px #888'},navOptions.menuStyle))}
menu.hideMenu=function(){css(menu,{display:'none'});if(button){button.setState(0)}
chart.openMenu=!1;css(chart.renderTo,{overflow:'hidden'});U.clearTimeout(menu.hideTimer);fireEvent(chart,'exportMenuHidden')};chart.exportEvents.push(addEvent(menu,'mouseleave',function(){menu.hideTimer=win.setTimeout(menu.hideMenu,500)}),addEvent(menu,'mouseenter',function(){U.clearTimeout(menu.hideTimer)}),addEvent(doc,'mouseup',function(e){if(!chart.pointer.inClass(e.target,className)){menu.hideMenu()}}),addEvent(menu,'click',function(){if(chart.openMenu){menu.hideMenu()}}));items.forEach(function(item){if(typeof item==='string'){item=chart.options.exporting.menuItemDefinitions[item]}
if(isObject(item,!0)){var element;if(item.separator){element=createElement('hr',null,null,innerMenu)}else{element=createElement('li',{className:'highcharts-menu-item',onclick:function(e){if(e){e.stopPropagation()}
menu.hideMenu();if(item.onclick){item.onclick.apply(chart,arguments)}},innerHTML:(item.text||chart.options.lang[item.textKey])},null,innerMenu);if(!chart.styledMode){element.onmouseover=function(){css(this,navOptions.menuItemHoverStyle)};element.onmouseout=function(){css(this,navOptions.menuItemStyle)};css(element,extend({cursor:'pointer'},navOptions.menuItemStyle))}}
chart.exportDivElements.push(element)}});chart.exportDivElements.push(innerMenu,menu);chart.exportMenuWidth=menu.offsetWidth;chart.exportMenuHeight=menu.offsetHeight}
menuStyle={display:'block'};if(x+chart.exportMenuWidth>chartWidth){menuStyle.right=(chartWidth-x-width-menuPadding)+'px'}else{menuStyle.left=(x-menuPadding)+'px'}
if(y+height+chart.exportMenuHeight>chartHeight&&button.alignOptions.verticalAlign!=='top'){menuStyle.bottom=(chartHeight-y-menuPadding)+'px'}else{menuStyle.top=(y+height-menuPadding)+'px'}
css(menu,menuStyle);css(chart.renderTo,{overflow:''});chart.openMenu=!0;fireEvent(chart,'exportMenuShown')},addButton:function(options){var chart=this,renderer=chart.renderer,btnOptions=merge(chart.options.navigation.buttonOptions,options),onclick=btnOptions.onclick,menuItems=btnOptions.menuItems,symbol,button,symbolSize=btnOptions.symbolSize||12;if(!chart.btnCount){chart.btnCount=0}
if(!chart.exportDivElements){chart.exportDivElements=[];chart.exportSVGElements=[]}
if(btnOptions.enabled===!1){return}
var attr=btnOptions.theme,states=attr.states,hover=states&&states.hover,select=states&&states.select,callback;if(!chart.styledMode){attr.fill=pick(attr.fill,'#ffffff');attr.stroke=pick(attr.stroke,'none')}
delete attr.states;if(onclick){callback=function(e){if(e){e.stopPropagation()}
onclick.call(chart,e)}}else if(menuItems){callback=function(e){if(e){e.stopPropagation()}
chart.contextMenu(button.menuClassName,menuItems,button.translateX,button.translateY,button.width,button.height,button);button.setState(2)}}
if(btnOptions.text&&btnOptions.symbol){attr.paddingLeft=pick(attr.paddingLeft,25)}else if(!btnOptions.text){extend(attr,{width:btnOptions.width,height:btnOptions.height,padding:0})}
if(!chart.styledMode){attr['stroke-linecap']='round';attr.fill=pick(attr.fill,'#ffffff');attr.stroke=pick(attr.stroke,'none')}
button=renderer.button(btnOptions.text,0,0,callback,attr,hover,select).addClass(options.className).attr({title:pick(chart.options.lang[btnOptions._titleKey||btnOptions.titleKey],'')});button.menuClassName=(options.menuClassName||'highcharts-menu-'+chart.btnCount++);if(btnOptions.symbol){symbol=renderer.symbol(btnOptions.symbol,btnOptions.symbolX-(symbolSize/2),btnOptions.symbolY-(symbolSize/2),symbolSize,symbolSize,{width:symbolSize,height:symbolSize}).addClass('highcharts-button-symbol').attr({zIndex:1}).add(button);if(!chart.styledMode){symbol.attr({stroke:btnOptions.symbolStroke,fill:btnOptions.symbolFill,'stroke-width':btnOptions.symbolStrokeWidth||1})}}
button.add(chart.exportingGroup).align(extend(btnOptions,{width:button.width,x:pick(btnOptions.x,chart.buttonOffset)}),!0,'spacingBox');chart.buttonOffset+=((button.width+btnOptions.buttonSpacing)*(btnOptions.align==='right'?-1:1));chart.exportSVGElements.push(button,symbol)},destroyExport:function(e){var chart=e?e.target:this,exportSVGElements=chart.exportSVGElements,exportDivElements=chart.exportDivElements,exportEvents=chart.exportEvents,cacheName;if(exportSVGElements){exportSVGElements.forEach(function(elem,i){if(elem){elem.onclick=elem.ontouchstart=null;cacheName='cache-'+elem.menuClassName;if(chart[cacheName]){delete chart[cacheName]}
chart.exportSVGElements[i]=elem.destroy()}});exportSVGElements.length=0}
if(chart.exportingGroup){chart.exportingGroup.destroy();delete chart.exportingGroup}
if(exportDivElements){exportDivElements.forEach(function(elem,i){U.clearTimeout(elem.hideTimer);removeEvent(elem,'mouseleave');chart.exportDivElements[i]=elem.onmouseout=elem.onmouseover=elem.ontouchstart=elem.onclick=null;discardElement(elem)});exportDivElements.length=0}
if(exportEvents){exportEvents.forEach(function(unbind){unbind()});exportEvents.length=0}}});SVGRenderer.prototype.inlineToAttributes=['fill','stroke','strokeLinecap','strokeLinejoin','strokeWidth','textAnchor','x','y'];SVGRenderer.prototype.inlineBlacklist=[/-/,/^(clipPath|cssText|d|height|width)$/,/^font$/,/[lL]ogical(Width|Height)$/,/perspective/,/TapHighlightColor/,/^transition/,/^length$/];SVGRenderer.prototype.unstyledElements=['clipPath','defs','desc'];Chart.prototype.inlineStyles=function(){var renderer=this.renderer,inlineToAttributes=renderer.inlineToAttributes,blacklist=renderer.inlineBlacklist,whitelist=renderer.inlineWhitelist,unstyledElements=renderer.unstyledElements,defaultStyles={},dummySVG,iframe,iframeDoc;iframe=doc.createElement('iframe');css(iframe,{width:'1px',height:'1px',visibility:'hidden'});doc.body.appendChild(iframe);iframeDoc=iframe.contentWindow.document;iframeDoc.open();iframeDoc.write('<svg xmlns="http://www.w3.org/2000/svg"></svg>');iframeDoc.close();function hyphenate(prop){return prop.replace(/([A-Z])/g,function(a,b){return'-'+b.toLowerCase()})}
function recurse(node){var styles,parentStyles,cssText='',dummy,styleAttr,blacklisted,whitelisted,i;function filterStyles(val,prop){blacklisted=whitelisted=!1;if(whitelist){i=whitelist.length;while(i--&&!whitelisted){whitelisted=whitelist[i].test(prop)}
blacklisted=!whitelisted}
if(prop==='transform'&&val==='none'){blacklisted=!0}
i=blacklist.length;while(i--&&!blacklisted){blacklisted=(blacklist[i].test(prop)||typeof val==='function')}
if(!blacklisted){if((parentStyles[prop]!==val||node.nodeName==='svg')&&defaultStyles[node.nodeName][prop]!==val){if(inlineToAttributes.indexOf(prop)!==-1){node.setAttribute(hyphenate(prop),val)}else{cssText+=hyphenate(prop)+':'+val+';'}}}}
if(node.nodeType===1&&unstyledElements.indexOf(node.nodeName)===-1){styles=win.getComputedStyle(node,null);parentStyles=node.nodeName==='svg'?{}:win.getComputedStyle(node.parentNode,null);if(!defaultStyles[node.nodeName]){dummySVG=iframeDoc.getElementsByTagName('svg')[0];dummy=iframeDoc.createElementNS(node.namespaceURI,node.nodeName);dummySVG.appendChild(dummy);defaultStyles[node.nodeName]=merge(win.getComputedStyle(dummy,null));if(node.nodeName==='text'){delete defaultStyles.text.fill}
dummySVG.removeChild(dummy)}
if(isFirefoxBrowser||isMSBrowser){for(var p in styles){filterStyles(styles[p],p)}}else{objectEach(styles,filterStyles)}
if(cssText){styleAttr=node.getAttribute('style');node.setAttribute('style',(styleAttr?styleAttr+';':'')+cssText)}
if(node.nodeName==='svg'){node.setAttribute('stroke-width','1px')}
if(node.nodeName==='text'){return}[].forEach.call(node.children||node.childNodes,recurse)}}
function tearDown(){dummySVG.parentNode.removeChild(dummySVG)}
recurse(this.container.querySelector('svg'));tearDown()};symbols.menu=function(x,y,width,height){var arr=['M',x,y+2.5,'L',x+width,y+2.5,'M',x,y+height/2+0.5,'L',x+width,y+height/2+0.5,'M',x,y+height-1.5,'L',x+width,y+height-1.5];return arr};symbols.menuball=function(x,y,width,height){var path=[],h=(height/3)-2;path=path.concat(this.circle(width-h,y,h,h),this.circle(width-h,y+h+4,h,h),this.circle(width-h,y+2*(h+4),h,h));return path};Chart.prototype.renderExporting=function(){var chart=this,exportingOptions=chart.options.exporting,buttons=exportingOptions.buttons,isDirty=chart.isDirtyExporting||!chart.exportSVGElements;chart.buttonOffset=0;if(chart.isDirtyExporting){chart.destroyExport()}
if(isDirty&&exportingOptions.enabled!==!1){chart.exportEvents=[];chart.exportingGroup=chart.exportingGroup||chart.renderer.g('exporting-group').attr({zIndex:3}).add();objectEach(buttons,function(button){chart.addButton(button)});chart.isDirtyExporting=!1}
addEvent(chart,'destroy',chart.destroyExport)};addEvent(Chart,'init',function(){var chart=this;function update(prop,options,redraw){chart.isDirtyExporting=!0;merge(!0,chart.options[prop],options);if(pick(redraw,!0)){chart.redraw()}}
chart.exporting={update:function(options,redraw){update('exporting',options,redraw)}};chartNavigationMixin.addUpdate(function(options,redraw){update('navigation',options,redraw)},chart)});Chart.prototype.callbacks.push(function(chart){chart.renderExporting();addEvent(chart,'redraw',chart.renderExporting)})});_registerModule(_modules,'masters/modules/exporting.src.js',[],function(){})}))